name: Deploy TEST

on:
    pull_request:
        branches: develop

permissions:
    id-token: write
    contents: read
    checks: write

jobs:
    build-and-test:
        name: Build and test code
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4